# Generated by Django 5.1.6 on 2025-03-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_integration_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMIntegration',
            fields=[
                ('SalM_No', models.IntegerField(blank=True, null=True)),
                ('SalM_Branch', models.SmallIntegerField(blank=True, null=True)),
                ('SalM_Type', models.SmallIntegerField(blank=True, null=True)),
                ('bIntegrated', models.BooleanField(blank=True, null=True)),
                ('strTransactionType', models.CharField(blank=True, max_length=1, null=True)),
                ('dateEntry', models.DateTimeField(blank=True, null=True)),
                ('dateIntegration', models.DateTimeField(blank=True, null=True)),
                ('lngTransaction', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'SalesM_Integration',
            },
        ),
    ]
