# Generated by Django 5.1.6 on 2025-03-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_integration_app', '0002_salesmintegration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesmintegration',
            old_name='bIntegrated',
            new_name='bintegrated',
        ),
        migrations.RenameField(
            model_name='salesmintegration',
            old_name='dateEntry',
            new_name='dateentry',
        ),
        migrations.RenameField(
            model_name='salesmintegration',
            old_name='dateIntegration',
            new_name='dateintegration',
        ),
        migrations.RenameField(
            model_name='salesmintegration',
            old_name='lngTransaction',
            new_name='lngtransaction',
        ),
        migrations.RenameField(
            model_name='salesmintegration',
            old_name='SalM_Branch',
            new_name='salm_branch',
        ),
        migrations.RenameField(
            model_name='salesmintegration',
            old_name='SalM_No',
            new_name='salm_no',
        ),
        migrations.RenameField(
            model_name='salesmintegration',
            old_name='SalM_Type',
            new_name='salm_type',
        ),
        migrations.RenameField(
            model_name='salesmintegration',
            old_name='strTransactionType',
            new_name='strtransactiontype',
        ),
    ]
