# Generated by Django 5.1.6 on 2025-03-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_integration_app', '0003_rename_bintegrated_salesmintegration_bintegrated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_no', models.FloatField(blank=True, null=True)),
                ('rec_date', models.DateTimeField(blank=True, null=True)),
                ('rec_amount', models.FloatField(blank=True, null=True)),
                ('rec_customer', models.FloatField(blank=True, null=True)),
                ('rec_branch', models.SmallIntegerField(blank=True, null=True)),
                ('rec_description', models.CharField(blank=True, max_length=120, null=True)),
                ('rec_cheque', models.FloatField(blank=True, null=True)),
                ('rec_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('rec_remark', models.CharField(blank=True, max_length=150, null=True)),
                ('rec_user', models.SmallIntegerField(blank=True, null=True)),
                ('rec_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('rec_aflag', models.CharField(blank=True, max_length=1, null=True)),
                ('rec_invoice_no', models.FloatField(blank=True, null=True)),
                ('rec_type', models.SmallIntegerField(blank=True, null=True)),
                ('rec_key', models.CharField(blank=True, max_length=50, null=True)),
                ('rec_account', models.FloatField(blank=True, null=True)),
                ('rec_voucher', models.FloatField(blank=True, null=True)),
                ('rec_vtype', models.SmallIntegerField(blank=True, null=True)),
                ('rec_cost_center', models.FloatField(blank=True, null=True)),
                ('rec_cost_item', models.FloatField(blank=True, null=True)),
                ('rec_collect', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Receipt',
            },
        ),
        migrations.AddField(
            model_name='salesmintegration',
            name='strsource',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
