# Generated by Django 5.1.6 on 2025-03-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_integration_app', '0004_receipt_salesmintegration_strsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmintegration',
            name='rec_branch',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesmintegration',
            name='rec_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesmintegration',
            name='rec_type',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
