# Generated by Django 5.1.6 on 2025-03-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_integration_app', '0008_suppcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppcard',
            name='scd_document',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
