# Generated by Django 5.1.6 on 2025-03-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_integration_app', '0009_alter_suppcard_scd_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuppCard',
        ),
    ]
