# Generated by Django 5.1.6 on 2025-03-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_integration_app', '0010_delete_suppcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppCard',
            fields=[
                ('scd_serial', models.AutoField(primary_key=True, serialize=False)),
                ('scd_code', models.CharField(blank=True, max_length=255, null=True)),
                ('scd_date', models.DateTimeField(blank=True, null=True)),
                ('scd_debit', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('scd_credit', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('scd_branch', models.SmallIntegerField(blank=True, null=True)),
                ('scd_document', models.FloatField(blank=True, null=True)),
                ('scd_type', models.CharField(blank=True, max_length=255, null=True)),
                ('scd_voucher', models.CharField(blank=True, max_length=255, null=True)),
                ('scd_description', models.TextField(blank=True, null=True)),
                ('str_voucherno', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'SuppCard',
            },
        ),
    ]
