# Generated by Django 5.1.6 on 2025-04-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_integration_app', '0011_suppcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmintegration',
            name='vom_no',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesmintegration',
            name='vom_type',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
