# Generated by Django 5.1.6 on 2025-04-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_integration_app', '0012_salesmintegration_vom_no_salesmintegration_vom_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmintegration',
            name='Vom_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
