# Generated by Django 5.1.6 on 2025-04-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_integration_app', '0013_salesmintegration_vom_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesmintegration',
            old_name='Vom_Date',
            new_name='vom_date',
        ),
    ]
